substitutions:
  project: bedroom
  id: bedsensor
  friendly_name: Bed sensor

packages:
  base: !include common/base.yaml
  device: !include common/devices/wemos-d1.yaml

##### Sensors
number:
  - platform: template
    name: "Occupancy threshold"
    entity_category: config
    id: threshold
    optimistic: true
    restore_value: true
    initial_value: 20
    min_value: 0
    max_value: 100
    step: 1
    mode: box

  - platform: template
    name: "Value multiplier"
    entity_category: config
    id: multiplier
    optimistic: true
    restore_value: true
    initial_value: 20
    mode: box
    min_value: 0
    max_value: 10
    step: 0.1

binary_sensor:
  - platform: template
    name: "Bed occupied"
    device_class: occupancy
    lambda: |-
      if (id(movement).state > id(threshold).state) {
        return true;
      } else {
        return false;
      }
    filters:
      - delayed_on_off: 1s

sensor:
  - platform: adc
    pin: A0
    name: "Bed movement"
    id: movement
    disabled_by_default: true
    entity_category: diagnostic
    update_interval: 100ms
    unit_of_measurement: "%"
    filters:
      - multiply: !lambda return id(multiplier).state;
      - sliding_window_moving_average:
          window_size: 10
          send_every: 10
      - calibrate_linear:
          method: exact
          datapoints:
            -  0.0 ->   0.0
            -  1.0 ->   100
      - delta: 1.0