substitutions:
  project: bedroom
  id: screen-lights

esphome:
  name: $id

esp8266:
  board: nodemcuv2

#<<: !include common/logging.yaml
#<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/wifi.yaml
#<<: !include common/mqtt.yaml

#sensor:
#  - !include common/sensor/wifi_signal.yaml

##### Light strip

#output:
#  - platform: esp8266_pwm
#    id: pwm_red
#    pin: D2
#    frequency: 1000 Hz
#  - platform: esp8266_pwm
#    id: pwm_green
#    pin: D6
#    frequency: 1000 Hz
#  - platform: esp8266_pwm
#    id: pwm_blue
#    pin: D5
#    frequency: 1000 Hz
#  - platform: esp8266_pwm
#    id: pwm_white
#    pin: D7
#    frequency: 1000 Hz
#
#light:
#  - platform: rgbw
#    name: "LED Strip"
#    red: pwm_red
#    green: pwm_green
#    blue: pwm_blue
#    white: pwm_white
#    color_interlock: true