substitutions:
  id: birdhouse
  friendly_name: Bird feeder

packages:
  base: !include common/base.yaml
  device: !include common/devices/esp32s3.yaml

### Custom stuff
esphome:
  platformio_options:
    build_flags: -DBOARD_HAS_PSRAM
    board_build.arduino.memory_type: qio_opi
    board_build.f_flash: 80000000L
    board_build.flash_mode: qio

logger:
  baud_rate: 0

esp32_camera:
  name: Bird Cam
  resolution: 1024x768
  jpeg_quality: 20
  max_framerate: 30 fps
  idle_framerate: 1 fps
  wb_mode: cloudy
  aec_mode: manual
  agc_mode: manual
  aec_value: 900
  agc_gain_ceiling: 2x

  external_clock:
    pin: GPIO10
    frequency: 20MHz
  i2c_pins:
    sda: GPIO40
    scl: GPIO39
  data_pins: [GPIO15, GPIO17, GPIO18, GPIO16, GPIO14, GPIO12, GPIO11, GPIO48]
  vsync_pin: GPIO38
  href_pin: GPIO47
  pixel_clock_pin: GPIO13

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot