substitutions:
  id: birdhouse
  friendly_name: Bird feeder

packages:
  base: !include common/base.yaml
  device: !include common/devices/esp32s3.yaml

### Custom stuff
esphome:
  platformio_options:
    build_flags: -DBOARD_HAS_PSRAM
    board_build.arduino.memory_type: qio_opi
    board_build.f_flash: 80000000L
    board_build.flash_mode: qio

logger:
  baud_rate: 0

globals:
  - id: frames
    type: int
    restore_value: no
    initial_value: '0'

esp32_camera:
  name: Bird Cam
  resolution: 800x600
  jpeg_quality: 20
  max_framerate: 30 fps
  idle_framerate: 1 fps
  wb_mode: cloudy
  aec_mode: auto
  aec_value: 600
  aec2: true
  ae_level: 1
  agc_mode: auto
  agc_gain_ceiling: 4x
  agc_value: 1
  brightness: 1

  external_clock:
    pin: GPIO10
    frequency: 20MHz
  i2c_pins:
    sda: GPIO40
    scl: GPIO39
  data_pins: [GPIO15, GPIO17, GPIO18, GPIO16, GPIO14, GPIO12, GPIO11, GPIO48]
  vsync_pin: GPIO38
  href_pin: GPIO47
  pixel_clock_pin: GPIO13
  on_image:
    then:
      - globals.set:
          id: frames
          value: !lambda 'return id(frames) + 1;'

number:
  - platform: template
    id: fps
    name: FPS
    icon: mdi:video
    unit_of_measurement: 'fps'
    optimistic: true
    step: 0.1
    max_value: 100
    min_value: 0

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot

interval:
  - interval: 30s
    then:
      - number.set:
          id: fps
          value: !lambda 'return id(frames) / 30.0;'
      - globals.set:
          id: frames
          value: '0'
