substitutions:
  project: any
  id: bluetooth-proxy
  friendly_name: Bluetooth Proxy

packages:
  base: !include common/base.yaml
  device: !include common/devices/lolin32-lite.yaml

### Bluetooth proxy

bluetooth_proxy:
  active: true

esp32_ble_tracker:
