substitutions:
  project: any
  id: bluetooth-proxy-02
  friendly_name: Bluetooth Proxy 02

packages:
  base: !include common/base.yaml
  device: !include common/devices/m5stack-atom-lite.yaml

### Bluetooth proxy

bluetooth_proxy:
  active: true

esp32_ble_tracker:
  scan_parameters:
    interval: 500ms
    window: 450ms
