substitutions:
  id: filament-tagger
  friendly_name: Filament Tagger

packages:
  base: !include common/base.yaml
  device: !include common/devices/esp32c3.yaml

##### Sensors

i2c:
  sda: GPIO6
  scl: GPIO7
  scan: true

pn532_i2c:
  update_interval: 200ms
  on_tag:
    then:
      - lambda: |-
          id(rfid_tag).publish_state(x);
          if (!tag.has_ndef_message()) {
            return;
          }
          auto message = tag.get_ndef_message();
          auto records = message->get_records();
          if(records.size() != 1) {
            return;
          }
          
          auto record = records[0];
          std::string payload = record->get_payload();
          
          if(payload.rfind("spool:", 0) == 0) {
              id(spool_id).publish_state(payload.substr(6));
          }

http_request:
  verify_ssl: false
  timeout: 15s

text_sensor:
  - platform: template
    name: "RFID Tag"
    id: rfid_tag

  - platform: template
    name: "Spool ID"
    id: spool_id

    on_value:
      then:
        - script.execute: beep_success
        - http_request.post:
            url: "http://192.168.1.245/printer/gcode/script"
            headers:
              Content-Type: application/json
            json:
              script: !lambda |-
                return ((std::string) "MMU_GATE_MAP NEXT_SPOOLID="+x).c_str();
            on_response:
              then:
                - script.execute: beep_success
            on_error:
              then:
                - script.execute: beep_error

output:
  - platform: gpio
    pin: GPIO3
    id: buzzer

script:
  - id: beep_success
    then:
      - output.turn_on: buzzer
      - delay: 1000ms
      - output.turn_off: buzzer

  - id: beep_error
    then:
      - output.turn_on: buzzer
      - delay: 300ms
      - output.turn_off: buzzer
      - delay: 200ms
      - output.turn_on: buzzer
      - delay: 300ms
      - output.turn_off: buzzer
      - delay: 200ms
      - output.turn_on: buzzer
      - delay: 300ms
      - output.turn_off: buzzer