substitutions:
  project: garage
  id: garage-gate

esphome:
  name: $id

esp8266:
  board: nodemcuv2

<<: !include common/logging.yaml
<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/wifi.yaml

##### Garage gate

binary_sensor:
  - platform: gpio
    pin:
      number: D7
      mode:
        input: true
        pullup: true
    name: "Gate Contact"
    device_class: garage_door
    filters:
      - delayed_on_off: 100ms

switch:
  - platform: gpio
    pin: D1
    id: relay
    name: "Gate Remote"
    icon: "mdi:gate"
    on_turn_on:
      - delay: 500ms
      - switch.turn_off: relay