substitutions:
  project: garden
  id: garden-sprinkler

esphome:
  name: $id

esp8266:
  board: nodemcuv2

<<: !include common/logging.yaml
<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/wifi.yaml

##### Irrigation control

sprinkler:
  - id: lawn_sprinkler_ctrlr
    main_switch: "Bewässerung"
    auto_advance_switch: "Auto-Modus"
    multiplier_number:
      name: "Laufzeit Multiplikator"
      initial_value: 1
      min_value: 0.1
      max_value: 3
    repeat_number:
      name: "Laufzeit wiederholen"
      initial_value: 0
      min_value: 0
      max_value: 3
    valve_overlap: 1s
    valves:
      - valve_switch: "Vorne 1"
        valve_switch_id: relay3
        enable_switch: "Vorne 1 aktiv"
        run_duration_number:
          name: "Vorne 1 Laufzeit"
          min_value: 10
          max_value: 1800

      - valve_switch: "Vorne 2"
        valve_switch_id: relay4
        enable_switch: "Vorne 2 aktiv"
        run_duration_number:
          name: "Vorne 2 Laufzeit"
          min_value: 10
          max_value: 1800

      - valve_switch: "Hinten 1"
        valve_switch_id: relay1
        enable_switch: "Hinten 1 aktiv"
        run_duration_number:
          name: "Hinten 1 Laufzeit"
          min_value: 10
          max_value: 1800

      - valve_switch: "Hinten 2"
        valve_switch_id: relay2
        enable_switch: "Hinten 2 aktiv"
        run_duration_number:
          name: "Hinten 2 Laufzeit"
          min_value: 10
          max_value: 1800

switch:
# Hinten Ecke
  - platform: gpio
    id: relay1
    pin: D1
    restore_mode: ALWAYS_OFF
    inverted: true

# Hinten Balkon
  - platform: gpio
    id: relay2
    pin: D2
    restore_mode: ALWAYS_OFF
    inverted: true

# Vorne Haus
  - platform: gpio
    id: relay3
    pin: D3
    restore_mode: ALWAYS_OFF
    inverted: true

# Vorne Einfahrt
  - platform: gpio
    id: relay4
    pin: D4
    restore_mode: ALWAYS_OFF
    inverted: true

