substitutions:
  project: any
  id: test
  friendly_name: test

packages:
  base: !include common/base.yaml
  mqtt: !include common/mqtt.yaml
  device: !include common/devices/esp32s3.yaml

api: null
# Enable logging
logger:
  level: INFO

wifi:
  fast_connect: true

deep_sleep:
  id: deep_sleep_1
  sleep_duration: 30min

globals:
  - id: ota_mode
    type: bool
    initial_value: 'false'

mqtt:
  topic_prefix: "diy/test"
  birth_message:
    topic: "diy/dontcare"
    payload: ""
  will_message:
    topic: "diy/dontcare"
    payload: ""

  on_message:
    - topic: diy/test/ota_mode
      payload: 'ON'
      then:
        - globals.set:
            id: ota_mode
            value: 'true'
    - topic: diy/test/ota_mode
      payload: 'OFF'
      then:
        - globals.set:
            id: ota_mode
            value: 'false'

    - topic: diy/test/sensor/moisture/state
      then:
        - if:
            condition:
              lambda: 'return !id(ota_mode);'
            then:
              - deep_sleep.enter: deep_sleep_1

esp32_touch:
  id: esp32_touch_1
  setup_mode: false

  measurement_duration: 100us
  denoise_grade: BIT12
  denoise_cap_level: L0
  debounce_count: 1
  filter_mode: IIR_16
  noise_threshold: 0
  jitter_step: 0
  smooth_mode: IIR_2

binary_sensor:
  - platform: esp32_touch
    internal: true
    id: touch_pin
    pin: GPIO12
    threshold: 100000

esphome:
  on_boot:
    priority: 200
    then:
      - sensor.template.publish:
          id: moisture
          state: !lambda |-
            auto raw_value = id(touch_pin).get_value();
            auto min_value = id(value_dry).state;
            auto max_value = id(value_wet).state;
            return (raw_value - min_value) / (max_value - min_value) * 100.0f;

sensor:
  - platform: template
    id: moisture
    name: "Moisture"
    unit_of_measurement: "%"
    device_class: moisture
    icon: "mdi:water-percent"

number:
  - platform: template
    name: "Moisture value dry"
    id: value_dry
    optimistic: true
    restore_value: true
    initial_value: 200000
    min_value: 0
    max_value: 5000000
    step: 1000
    entity_category: config


  - platform: template
    name: "Moisture value wet"
    id: value_wet
    optimistic: true
    restore_value: true
    initial_value: 2000000
    min_value: 0
    max_value: 5000000
    step: 1000
    entity_category: config