substitutions:
  project: any
  id: mini-speaker
  friendly_name: Mini Speaker

packages:
  base: !include common/base.yaml
  device: !include common/devices/esp32s3.yaml

# Enable logging
logger:
  level: INFO

wifi:
  fast_connect: true

i2s_audio:
  - id: i2s_in
    i2s_lrclk_pin: 03
    i2s_bclk_pin: 02

microphone:
  platform: i2s_audio
  id: external_microphone
  adc_type: external
  i2s_audio_id: i2s_in
  i2s_din_pin: 13
  pdm: false

voice_assistant:
  microphone: external_microphone
