substitutions:
  project: garden
  id: mower-garage-sensor

esphome:
  name: $id

esp8266:
  board: nodemcuv2

<<: !include common/logging.yaml
<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/wifi.yaml

##### Mower garage sensor

sensor:
  - platform: dht
    pin: D2
    update_interval: 6s
    temperature:
      name: "Outside Temperature"
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 10
            send_first_at: 10
    humidity:
      name: "Outside Humidity"
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 10
            send_first_at: 10

  - platform: adc
    pin: A0
    id: moisture_sensor_raw
    update_interval: 6s
    filters:
      - calibrate_linear:
          - 0.5 -> 0.0
          - 0.2 -> 100.0

  - platform: copy
    id: moisture_sensor_fast
    source_id: moisture_sensor_raw
    name: "Soil Moisture (fast)"
    device_class: "moisture"
    state_class: "measurement"
    unit_of_measurement: "%"
    icon: "mdi:water-percent"
    accuracy_decimals: 1
    filters:
      - sliding_window_moving_average:
          window_size: 10   # 10 times 6s per reading = 60s / 1m of averaging
          send_every: 10    # 10 times 6s per reading = 60s / 1m between signals
          send_first_at: 10

  - platform: copy
    id: moisture_sensor_avg
    source_id: moisture_sensor_raw
    name: "Soil Moisture (avg)"
    device_class: "moisture"
    state_class: "measurement"
    unit_of_measurement: "%"
    icon: "mdi:water-percent"
    accuracy_decimals: 1
    filters:
      - sliding_window_moving_average:
          window_size: 1200  # 1200 times 6s per reading = 7200s / 120m /2h of averaging
          send_every: 100    # 100 times 6s per reading = 600s / 10m between signals
          send_first_at: 100