substitutions:
  project: any
  id: plant-sensor-01
  friendly_name: Plant sensor 01

packages:
  base: !include common/base.yaml
  device: !include common/devices/esp32c3.yaml

wifi:
  fast_connect: true

#deep_sleep:
#  id: deep_sleep_1
#  sleep_duration: 30min
#  run_duration: 10sec

globals:
  - id: ota_mode
    type: bool
    initial_value: 'false'

#esp32_touch:
#  id: esp32_touch_1
#  setup_mode: false
#
#  measurement_duration: 100us
#  denoise_grade: BIT12
#  denoise_cap_level: L0
#  debounce_count: 1
#  filter_mode: IIR_16
#  noise_threshold: 0
#  jitter_step: 0
#  smooth_mode: IIR_2

#binary_sensor:
#  - platform: esp32_touch
#    internal: true
#    id: touch_pin
#    pin: 10
#    threshold: 100000

sensor:
  - platform: adc
    pin: 1
    attenuation: 11db
    name: "Battery Voltage"
    filters:
      - calibrate_linear:
          - 0.0 -> 0.0
          - 1.22 -> 4.00

#  - platform: template
#    id: moisture
#    name: "Moisture"
#    unit_of_measurement: "%"
#    device_class: moisture
#    icon: "mdi:water-percent"
#    update_interval: 5s
#    lambda: |-
#      auto raw_value = id(touch_pin).get_value();
#      auto min_value = id(value_dry).state;
#      auto max_value = id(value_wet).state;
#      return (raw_value - min_value) / (max_value - min_value) * 100.0f;

number:
  - platform: template
    name: "Moisture value dry"
    id: value_dry
    optimistic: true
    restore_value: true
    initial_value: 200000
    min_value: 0
    max_value: 5000000
    step: 1000
    entity_category: config


  - platform: template
    name: "Moisture value wet"
    id: value_wet
    optimistic: true
    restore_value: true
    initial_value: 2000000
    min_value: 0
    max_value: 5000000
    step: 1000
    entity_category: config