substitutions:
  project: hwr
  id: power-meter

esphome:
  name: $id
  includes:
    - power-meter.h

esp8266:
  board: d1_mini_pro

<<: !include common/logging.yaml
<<: !include common/api.yaml
<<: !include common/ota.yaml
<<: !include common/wifi.yaml
<<: !include common/mqtt.yaml

sensor:
  - !include common/sensor/wifi_signal.yaml

  - platform: custom
    lambda: |-
      auto power_sensor = new MyPowerSensor(60);
      App.register_component(power_sensor);
      return {power_sensor};
      
    sensors:
      name: "Stromverbrauch"
      unit_of_measurement: kW
      accuracy_decimals: 2