substitutions:
  project: home
  id: sonoff-socket-01
  friendly_name: Sonoff Socket 01

packages:
  base: !include common/base.yaml
  device: !include common/devices/esp01_1m.yaml

##### Device specific

# Sonoff S20

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff S20 Button"
    on_press:
      - switch.toggle: relay

  - platform: status
    name: "Sonoff S20 Status"

switch:
  - platform: gpio
    name: "Sonoff S20 Relay"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: true