substitutions:
  project: any
  id: thorsten-lichterkette
  friendly_name: Thorsten Lichterkette

packages:
  base: !include common/base.yaml
  device: !include common/devices/esp32s3.yaml

### Custom stuff

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO06
    num_leds: 50
    rmt_channel: 0
    chipset: ws2812
    name: "Licht"