substitutions:
  project: any
  id: thorsten-lichterkette
  friendly_name: Thorsten Lichterkette

packages:
  base: !include common/base.yaml
  device: !include common/devices/esp32s3.yaml

### Custom stuff
output:
  - platform: ledc
    pin: 43
    frequency: 2441 Hz
    id: pwm_output

light:
  - platform: monochromatic
    output: pwm_output
    name: "Licht"
