---

# Enable wifi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

  # Fallback Hotspot (requires "captive_portal:").
  ap:
    ssid: $id
    password: !secret wifi_pass_failover

captive_portal:

web_server:

sensor:
  - platform: wifi_signal
    name: WiFi Signal
    update_interval: 30s

  - platform: uptime
    name: Uptime Sensor